package com.example.data.api

import android.util.Log
import com.example.BuildConfig
import com.squareup.moshi.Json
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Query
import java.util.concurrent.TimeUnit

// --- Gemini Request / Response Models ---

data class Part(
    @Json(name = "text") val text: String? = null
)

data class Content(
    @Json(name = "parts") val parts: List<Part>,
    @Json(name = "role") val role: String? = null
)

data class GenerateContentRequest(
    @Json(name = "contents") val contents: List<Content>,
    @Json(name = "systemInstruction") val systemInstruction: Content? = null
)

data class Candidate(
    @Json(name = "content") val content: Content? = null
)

data class GenerateContentResponse(
    @Json(name = "candidates") val candidates: List<Candidate>? = null
)

// --- Retrofit API Service ---

interface GeminiApiService {
    @POST("v1beta/models/gemini-3.5-flash:generateContent")
    suspend fun generateContent(
        @Query("key") apiKey: String,
        @Body request: GenerateContentRequest
    ): GenerateContentResponse
}

object GeminiClient {
    private const val TAG = "GeminiClient"
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"

    private val moshi = Moshi.Builder()
        .addLast(KotlinJsonAdapterFactory())
        .build()

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    val service: GeminiApiService by lazy {
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
            .create(GeminiApiService::class.java)
    }

    suspend fun generateContent(prompt: String, systemPrompt: String? = null): String {
        return try {
            val key = BuildConfig.GEMINI_API_KEY
            if (key == "MY_GEMINI_API_KEY" || key.isEmpty()) {
                return "The Gemini API Key is missing or not configured. Please add GEMINI_API_KEY in the Secrets panel in AI Studio to chat with the AI!"
            }

            val contents = listOf(Content(parts = listOf(Part(text = prompt))))
            val systemInstruction = systemPrompt?.let {
                Content(parts = listOf(Part(text = it)))
            }

            val request = GenerateContentRequest(
                contents = contents,
                systemInstruction = systemInstruction
            )

            val response = service.generateContent(key, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text 
                ?: "No response generated by the AI."
        } catch (e: Exception) {
            Log.e(TAG, "Error in generateContent: ${e.message}", e)
            "Error: ${e.localizedMessage ?: "Unknown error while communicating with Gemini."}"
        }
    }

    suspend fun generateChatResponse(history: List<com.example.data.model.ChatMessage>, systemPrompt: String): String {
        return try {
            val key = BuildConfig.GEMINI_API_KEY
            if (key == "MY_GEMINI_API_KEY" || key.isEmpty()) {
                return "API key not configured. Add GEMINI_API_KEY in the Secrets panel."
            }

            // Convert chat history to Gemini's format
            val contents = history.map { msg ->
                Content(
                    parts = listOf(Part(text = msg.content)),
                    role = if (msg.role == "user") "user" else "model"
                )
            }

            val systemInstruction = Content(parts = listOf(Part(text = systemPrompt)))
            val request = GenerateContentRequest(
                contents = contents,
                systemInstruction = systemInstruction
            )

            val response = service.generateContent(key, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text 
                ?: "No response from AI."
        } catch (e: Exception) {
            Log.e(TAG, "Error in generateChatResponse: ${e.message}", e)
            "Error: ${e.localizedMessage ?: "Unknown connection error."}"
        }
    }
}
