package com.example.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data model representing a user's Habit Entity for local database persistence.
 *
 * @param id Unique identifier for the habit, auto-generated by the database.
 * @param name The descriptive name of the habit (e.g., "Hydration", "Reading").
 * @param frequency The occurrence frequency of the habit (e.g., "Daily", "Weekly").
 * @param isCompleted Represents the current completion status of the habit.
 * @param goals User-defined goals or target description for the habit (e.g., "Drink 8 glasses of water").
 */
@Entity(tableName = "habit_entities")
data class HabitEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val name: String,
    val frequency: String,
    val isCompleted: Boolean = false,
    val goals: String
)
